### ISSUE TITLE
Version 2.0.10

### ISSUE THREAD

**Issue by reillysg** [monk-ee/SplunkAppforAWSBilling#10]
Hi Monkee : Thanks for 2.0.10 ! WE installed it this morning but still have a couple of issues with ProcessDetailedReport.py : 
1)it does not write to the aws-bill index but just to stdout (see line 236) - I've had to do a fair amount of hacking and splicing code from the ProcessOlderReport.py file to make it connect to Splunk.
2) also line 99 is wrong it shoulds read :  for month in range(-int(key['history']), 0):
and also line 14 of ProcessDetailedReport.py  has the same config issue  needs 'self.config' switching to 'key'

One final issue is that FetchDEtailedReport.py only gets the last month - not the most recent months data, i.e. it doesn't get Jan 2016 only Dec 2015 -  fixing that is beyond my feeble python

**Comment by monk-ee** [comment]
Hi,
     the ProcessDetailedReport is run as a Data Input - it is not a command line script. If your data inputs are configured correctly - as they should be when you install the application, the script is called by Splunk Internals. I can send you some screen shots as to what this looks like when it is configured correctly. 

Hence, why it just pushes to stdout if you run it from the CLI and the config variables are not set correctly.

I will look into the FetchDetaliedReport problem, that sounds pretty legit to me ;)

**Comment by monk-ee** [comment]
Hi Sue,
             if you go into the Settings > Data Inputs > Scripts Dialog you should see the following:
![image](https://cloud.githubusercontent.com/assets/365583/12341438/66588ad8-bb6d-11e5-9552-634edd487f7b.png)

There should be 3 entries related to the SplunkAppforAWSBilling:
- FetchDetailedReports.py
- ProcessDetailedReports.py
- MainatinDetailedReports.py

The first two should be enabled by default, this means that on a timed schedule (Interval) these scripts will be executed. This is the method the application uses to fetch the data and process it. There is no need for any manual effort on your part.
