### ISSUE TITLE
ERROR	fetch_detailed_report:109 - Failed to get file from s3: S3ResponseError: 400 Bad Request

### ISSUE THREAD

**Issue by stremetznet** [monk-ee/SplunkAppforAWSBilling#2]
I have been able to install the AWSBilling App for Splunk, but was never able to fetch the reports from my S3 bucket.

When using the awscli, I can verify that I'm able to access my bucket and the files in it, using the security credentials I set in the was.yaml file for the BillingApp.

I have been trying to do manual fetches via
/opt/splunk/bin/splunk cmd python /opt/splunk/etc/apps/SplunkAppforAWSBilling/bin/fetch_detailed_report.py

But it takes just a second and shows the error written in the subject.

Please assist.

Thank you

**Comment by monk-ee** [comment]
Can you please let me know what version you are using? It would be better to upgrade to 2.0.5 and try again, as it has many functional improvements.

If the keys are correct, it seems to me that your account number in the aws.yaml file could be wrong.

**Comment by stremetznet** [comment]
Hello. I already upgraded to version 2.0.5.
Have been using the example aws.yaml file

**Comment by stremetznet** [comment]
Looks like that:

accounts:
- account_number : 123456789
  billing_bucket : my bucket
  aws_access_key : XXXXXXXXXXXXXXXXX
  aws_secret_key : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by monk-ee** [comment]
And you have put your account number into the account number space?

**Comment by monk-ee** [comment]
Do you know how to check your account number?

**Comment by stremetznet** [comment]
Account number is found in the account settings on AWS console?

**Comment by stremetznet** [comment]
Is there a way of doing a step by step debugging? The logs are not so much informative. I have been trying with awscli to access my bucket, that works fine.

**Comment by monk-ee** [comment]
To check your account number id correct go to the billing section in the AWS web console on go to "Account Settings". The number where the big pink arrow is pointing is your account number/id. That is the number you need to use  in the aws.yaml file

![image](https://cloud.githubusercontent.com/assets/365583/7829992/48b86956-048b-11e5-8856-39cb6f7cc8c6.png)

**Comment by stremetznet** [comment]
Verified. Was set correctly

**Comment by stremetznet** [comment]
2015-05-27 08:55:48,911 ERROR   fetch_detailed_report:109 - Failed to get file from s3: S3ResponseError: 400 Bad Request

**Comment by monk-ee** [comment]
OK, I will send you a debug version of that file - so you can run it and collect the logs for me.

**Comment by stremetznet** [comment]
Wonderful.

**Comment by stremetznet** [comment]
Where can I download it??
