### ISSUE TITLE
Repeat Loading +

### ISSUE THREAD

**Issue by reillysg** [monk-ee/SplunkAppforAWSBilling#8]
Hi Monkee
Just download version 2.0.9 and run into a few snags
1) The app unzips to SplunkAppforAWSBilling-2.0.0/  but refers throughout to SplunkAppforAWSBilling/
2) The splunk data-inputs for the app don't set up correctly - I get entries for
/opt/splunk/etc/apps/SplunkAppforAWSBilling-2.0.9/bin/ProcessDetailedReport.py  and
$SPLUNK_HOME/etc/apps/SplunkAppforAWSBilling-2.0.9/bin/FetchDetailedReport.py
but on inspection ProcessDetailed report just outputs to a text stream, not to splunk!
I cannot really figure out what entries I should have cronning in here that would give me incremental updates of data through the day : any advice
3) Picking through the code, ProcessOlderReport.py does seem to do the writing to splunk, but still has the fudge data routines you fixed in 2.05 - so looks un-patched
4) But if I run ProcessOlderReport.py  repeatedly for the same period - it does not remember it's place and so duplicates data. This stops me using this version in the crons.

Really hoping you can help as the app has served us brilliantly in the past
Cheers

**Comment by monk-ee** [comment]
Hi, 

Item 1) The splunk application format has changed so I have to rename the application- that is a a stuff up on my part I will raise a bug.
Item 2) No idea, I think the application does not like upgrading, still my bad I will raise a bug.
    Item 3) The ProcessOlderReport.py is now deprecated, the application will try to fetch the last 12 months of reports. Please don't use it.
Item 4) see Item 3 - do not run this - it should not even be in the package - this is probably an upgrade problem.
